sudo: false
language: bash
os:
- linux
script:
- cd package
- "./build_boards_manager_package.sh 1.0.1"
notifications:
  email:
    recipients:
    - bengchet@cytron.com.my
    on_success: change
    on_failure: change
